live_config_reload = true

[font]
size = 18.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 0.94
blur = true

[window.padding]
x = 14
y = 14

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
