live_config_reload = true

[font]
size = 18.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.95

[window.padding]
x = 14
y = 14
