live_config_reload = true

[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 0.94
blur = true

[window.padding]
x = 10
y = 10
